### ISSUE TITLE
Orderd Dictionary/Map

### ISSUE THREAD

**Issue by vuln3r** [unrelentingtech/SwiftCBOR#77]
Hi Folks,

is there any way to get the ordered map back?

`return CBOR.map([
            1: "key1",
            2: "key2",
            3: "key3",
            4: "key4",
        ])`

after this, I'm getting a random map each time and need to get ith sorted somehow.

Could you please help me with this?

**Comment by hamchapman** [comment]
Did you intentionally list repeated key-value pairs? 

Or are you asking about whether or not you can get SwiftCBOR to produce what the (most recent) [CBOR RFC defines as "Deterministic Encoding"](https://datatracker.ietf.org/doc/html/rfc8949#section-4.2.1)?

**Comment by hamchapman** [comment]
Even if we implemented something like the code in #50 you wouldn't necessarily get back a map ordered in the same way as the map was ordered when inserted it, because dictionaries in Swift aren't ordered (but you would get back something deterministic if we merged something like #50). You can write what _looks_ like an ordered map/dictionary but in reality it's not actually ordered. I know Swift know has some extra packages where you can get things like `OrderedDictionary` but I haven't tested how encoding works with them.

Understanding more about what you're trying to achieve and why would help, if possible.

**Comment by vuln3r** [comment]
Yes, my problem is that I need CBOR Map to be exactly as I define it in my example above because I'm using it for the decryption, and if the keys are not in the same position like I did define them then my decryption doesn't work :(

I would say it is more in the way of `OrderedDictionary`

**Comment by vuln3r** [comment]
But it could help, because my keys are always `Int` and if I read it correctly it needs to be sorted from 0 to ++

**Comment by vuln3r** [comment]
hi @hamchapman do you have any idea how I could solve it? I tried with #50 but it solves my problem partially because I have a map and inside a map another map and so.

**Comment by vuln3r** [comment]
I've solved it :) it was #50 ... thnx

**Comment by vuln3r** [comment]
I've solved it :) it was #50 ... thnx

**Comment by phisakel** [comment]
You can use my pull request [PR 96](https://github.com/valpackett/SwiftCBOR/pull/96)
